export default {
    "1.png": require("../../public/images/books/1.png"),
    "2.png": require("../../public/images/books/2.png"),
    "3.png": require("../../public/images/books/3.png"),
    "4.png": require("../../public/images/books/4.png"),
    "5.png": require("../../public/images/books/5.png"),
    "6.png": require("../../public/images/books/6.png"),
    "7.png": require("../../public/images/books/7.png"),
    "8.png": require("../../public/images/books/8.png"),
    "9.png": require("../../public/images/books/9.png"),
    "10.png": require("../../public/images/books/10.png"),
    "11.png": require("../../public/images/books/11.png"),
    "12.png": require("../../public/images/books/12.png"),
    "13.png": require("../../public/images/books/13.png"),
    "14.png": require("../../public/images/books/14.png"),
    "15.png": require("../../public/images/books/15.png"),
}